[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools-scm>=7"]
build-backend = "setuptools.build_meta"

[project]
name = "seastersdb"
description = "Python package to access the SEASTERS database."
authors = [{ name = "Quentin Desmet", email = "desmetque@gmail.com" }]
dynamic = ["version"]
requires-python = ">=3.10, <3.13"
license = { text = "MIT" }

dependencies = [
  "duckdb<1.4",
  "numpy",
  "pandas",
]

[project.optional-dependencies]
dev = [
  "isort",
  "black",
  "flake8",
  "flake8-pyproject",
  "mypy",
  "pre-commit",
]

[project.scripts]
seastersdb = "seastersdb.program.main:main"
seastersdb-locate = "seastersdb.program.locate:main"

[tool.setuptools_scm]
write_to = "seastersdb/_version.py"

[tool.isort]
profile = "black"
line_length = 88

[tool.black]
line-length = 88

[tool.flake8]
ignore = ["E501", "W503", "W604"]
exclude = ["examples/*", "utils/*"]
per-file-ignores = """
  */__init__.py: F401
"""

[tool.mypy]
exclude = '^(examples/|utils/)'
